spring:
  profiles:
    active: '@env@'

  servlet:
    multipart:
      max-file-size: 10MB # 限制单个文件上传最大为10MB
      max-request-size: 10MB # 限制多文件上传时大小总和最大为10MB

jwt:
  # 签发人
  issuer: CM
  # 秘钥
  secret: JUjN5GvIe/mc04kQA7I4Iy5CtroT5zUsYM29Iyu3RwYcpdh/ZcaYcJBDHrUuQINcyxuOiKX3prlNmuc7Y0868g==
  # Token 过期时间（分钟）
  tokenExpireTime: 1440
  # Token 请求头 key 值
  tokenHeaderKey: Authorization
  # Token 值前缀
  tokenPrefix: Bearer